name: Manual Publish

on:
  workflow_dispatch:
    inputs:
      publish_version:
        description: 'Version to publish to Docker Hub (e.g., 0.14.1.1)'
        required: true
        type: string

jobs:
  build:
    name: Manual Publish with Custom Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Publish with Custom Version
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target $(find . -type f -name "Dockerfile" -exec dirname {} \; | awk -F'/' '{print $NF}') \
            --docker-hub ${{ secrets.DOCKERHUB_USERNAME }} \
            --version ${{ inputs.publish_version }}